import type { Metadata } from "next";
import "@/styles/globals.scss";
import { ThemeProvider } from "@/lib/providers";
import { GeistSans } from "geist/font/sans";

export const metadata: Metadata = {
  title: "Architecture Skeleton Next App",
  description: "Generated by create next app & github.com/yuriipalamar"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body className="bg-background">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
