import type { Metadata } from "next";
import "@/styles/globals.scss";

export const metadata: Metadata = {
  title: "Architecture Skeleton Next App",
  description: "Generated by create next app & github.com/yuriipalamar"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-poppins">
        <main>{children}</main>
      </body>
    </html>
  );
}
